language: c
sudo: false

branches:
  only:
  - master
  - travis

cache:
  directories:
  - $HOME/.cabal/packages

before_cache:
  - rm -fv $HOME/.cabal/packages/*/build-reports.log
  - rm -fv $HOME/.cabal/packages/*/00-index.cache
  - rm -fv $HOME/.cabal/packages/*/00-index.tar

matrix:
  include:
    - env: CABALVER=1.22 GHCVER=7.10.3
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.3], sources: [hvr-ghc]}}
    - env: CABALVER=1.24 GHCVER=8.0.2
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.2], sources: [hvr-ghc]}}
    - env: CABALVER=head GHCVER=head
      addons: {apt: {packages: [cabal-install-head,ghc-head], sources: [hvr-ghc]}}
  allow_failures:
   - env: CABALVER=head GHCVER=head

install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
  - |
    CABALARGS=""
    if [ "x$GHCVER" = "xhead" ]; then CABALARGS=--allow-newer; fi
  - |
    travis_retry cabal update
    cabal install --only-dependencies --enable-tests --enable-benchmarks --force-reinstalls --ghc-options=-O0 --reorder-goals --max-backjumps=-1 $CABALARGS
    cabal install packdeps hlint

script:
- |
  set -ex
  cabal install --enable-tests --enable-benchmarks --force-reinstalls --ghc-options=-O0 --ghc-options=-Werror --reorder-goals --max-backjumps=-1 $CABALARGS
  cabal check
  packdeps mpd.cabal
  cabal test
  cabal sdist
  cabal install --force-reinstalls dist/mpd-*.tar.gz
  set +ex
